version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  api:
    build: ./LMSystemApi/LMSystemApi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Database=tododb;Username=postgres;Password=123456
    depends_on:
      - db
    expose:
      - "80"
    restart: always

  front:
    build: ./todo-front
    environment:
      - NODE_ENV=production
    expose:
      - "80"
    restart: always
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - front
      - api
    restart: always

volumes:
  pgdata: